package pojos;
// Generated 15-sep-2016 21:42:28 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cambio generated by hbm2java
 */
@Entity
@Table(name="cambio"
    ,catalog="almazaradb"
)
public class Cambio  implements java.io.Serializable {


     private Integer idCambio;
     private Cliente cliente;
     private Usuario usuario;
     private float kgOliva;
     private boolean paga;
     private boolean retira;
     private float rendimiento;
     private float litrosCambio;
     private float litrosRetirados;
     private float porcentajeMaquila;
     private float maquila;
     private float precioMolturacion;
     private float aceiteRetirado;
     private float totalPagar;
     private float maquilaReflejada;
     private float kgOlivaReflejados;
     private String poblacionOliva;
     private String observaciones;

    public Cambio() {
    }

	
    public Cambio(Cliente cliente, Usuario usuario, float kgOliva, boolean paga, boolean retira, float rendimiento, float litrosCambio, float litrosRetirados, float porcentajeMaquila, float maquila, float precioMolturacion, float aceiteRetirado, float totalPagar, float maquilaReflejada, float kgOlivaReflejados) {
        this.cliente = cliente;
        this.usuario = usuario;
        this.kgOliva = kgOliva;
        this.paga = paga;
        this.retira = retira;
        this.rendimiento = rendimiento;
        this.litrosCambio = litrosCambio;
        this.litrosRetirados = litrosRetirados;
        this.porcentajeMaquila = porcentajeMaquila;
        this.maquila = maquila;
        this.precioMolturacion = precioMolturacion;
        this.aceiteRetirado = aceiteRetirado;
        this.totalPagar = totalPagar;
        this.maquilaReflejada = maquilaReflejada;
        this.kgOlivaReflejados = kgOlivaReflejados;
    }
    public Cambio(Cliente cliente, Usuario usuario, float kgOliva, boolean paga, boolean retira, float rendimiento, float litrosCambio, float litrosRetirados, float porcentajeMaquila, float maquila, float precioMolturacion, float aceiteRetirado, float totalPagar, float maquilaReflejada, float kgOlivaReflejados, String poblacionOliva, String observaciones) {
       this.cliente = cliente;
       this.usuario = usuario;
       this.kgOliva = kgOliva;
       this.paga = paga;
       this.retira = retira;
       this.rendimiento = rendimiento;
       this.litrosCambio = litrosCambio;
       this.litrosRetirados = litrosRetirados;
       this.porcentajeMaquila = porcentajeMaquila;
       this.maquila = maquila;
       this.precioMolturacion = precioMolturacion;
       this.aceiteRetirado = aceiteRetirado;
       this.totalPagar = totalPagar;
       this.maquilaReflejada = maquilaReflejada;
       this.kgOlivaReflejados = kgOlivaReflejados;
       this.poblacionOliva = poblacionOliva;
       this.observaciones = observaciones;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCambio", unique=true, nullable=false)
    public Integer getIdCambio() {
        return this.idCambio;
    }
    
    public void setIdCambio(Integer idCambio) {
        this.idCambio = idCambio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Cliente_idCliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Usuario_idUsuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="kgOliva", nullable=false, precision=12, scale=0)
    public float getKgOliva() {
        return this.kgOliva;
    }
    
    public void setKgOliva(float kgOliva) {
        this.kgOliva = kgOliva;
    }

    
    @Column(name="paga", nullable=false)
    public boolean isPaga() {
        return this.paga;
    }
    
    public void setPaga(boolean paga) {
        this.paga = paga;
    }

    
    @Column(name="retira", nullable=false)
    public boolean isRetira() {
        return this.retira;
    }
    
    public void setRetira(boolean retira) {
        this.retira = retira;
    }

    
    @Column(name="rendimiento", nullable=false, precision=12, scale=0)
    public float getRendimiento() {
        return this.rendimiento;
    }
    
    public void setRendimiento(float rendimiento) {
        this.rendimiento = rendimiento;
    }

    
    @Column(name="litrosCambio", nullable=false, precision=12, scale=0)
    public float getLitrosCambio() {
        return this.litrosCambio;
    }
    
    public void setLitrosCambio(float litrosCambio) {
        this.litrosCambio = litrosCambio;
    }

    
    @Column(name="litrosRetirados", nullable=false, precision=12, scale=0)
    public float getLitrosRetirados() {
        return this.litrosRetirados;
    }
    
    public void setLitrosRetirados(float litrosRetirados) {
        this.litrosRetirados = litrosRetirados;
    }

    
    @Column(name="porcentajeMaquila", nullable=false, precision=12, scale=0)
    public float getPorcentajeMaquila() {
        return this.porcentajeMaquila;
    }
    
    public void setPorcentajeMaquila(float porcentajeMaquila) {
        this.porcentajeMaquila = porcentajeMaquila;
    }

    
    @Column(name="maquila", nullable=false, precision=12, scale=0)
    public float getMaquila() {
        return this.maquila;
    }
    
    public void setMaquila(float maquila) {
        this.maquila = maquila;
    }

    
    @Column(name="precioMolturacion", nullable=false, precision=12, scale=0)
    public float getPrecioMolturacion() {
        return this.precioMolturacion;
    }
    
    public void setPrecioMolturacion(float precioMolturacion) {
        this.precioMolturacion = precioMolturacion;
    }

    
    @Column(name="aceiteRetirado", nullable=false, precision=12, scale=0)
    public float getAceiteRetirado() {
        return this.aceiteRetirado;
    }
    
    public void setAceiteRetirado(float aceiteRetirado) {
        this.aceiteRetirado = aceiteRetirado;
    }

    
    @Column(name="totalPagar", nullable=false, precision=12, scale=0)
    public float getTotalPagar() {
        return this.totalPagar;
    }
    
    public void setTotalPagar(float totalPagar) {
        this.totalPagar = totalPagar;
    }

    
    @Column(name="maquilaReflejada", nullable=false, precision=12, scale=0)
    public float getMaquilaReflejada() {
        return this.maquilaReflejada;
    }
    
    public void setMaquilaReflejada(float maquilaReflejada) {
        this.maquilaReflejada = maquilaReflejada;
    }

    
    @Column(name="kgOlivaReflejados", nullable=false, precision=12, scale=0)
    public float getKgOlivaReflejados() {
        return this.kgOlivaReflejados;
    }
    
    public void setKgOlivaReflejados(float kgOlivaReflejados) {
        this.kgOlivaReflejados = kgOlivaReflejados;
    }

    
    @Column(name="poblacionOliva", length=30)
    public String getPoblacionOliva() {
        return this.poblacionOliva;
    }
    
    public void setPoblacionOliva(String poblacionOliva) {
        this.poblacionOliva = poblacionOliva;
    }

    
    @Column(name="Observaciones", length=100)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


