package pojos;
// Generated 13-sep-2016 20:37:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="almazaradb"
    , uniqueConstraints = {@UniqueConstraint(columnNames="dni"), @UniqueConstraint(columnNames="nombre")} 
)
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private String nombre;
     private String dni;
     private String direccion;
     private String telefono;
     private String poblacion;
     private boolean subvencionado;
     private Set ventas = new HashSet(0);
     private Set compras = new HashSet(0);
     private Set molturacions = new HashSet(0);
     private Set cambios = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int idCliente, String nombre, boolean subvencionado) {
        this.idCliente = idCliente;
        this.nombre = nombre;
        this.subvencionado = subvencionado;
    }
    public Cliente(int idCliente, String nombre, String dni, String direccion, String telefono, String poblacion, boolean subvencionado, Set ventas, Set compras, Set molturacions, Set cambios) {
       this.idCliente = idCliente;
       this.nombre = nombre;
       this.dni = dni;
       this.direccion = direccion;
       this.telefono = telefono;
       this.poblacion = poblacion;
       this.subvencionado = subvencionado;
       this.ventas = ventas;
       this.compras = compras;
       this.molturacions = molturacions;
       this.cambios = cambios;
    }
   
     @Id 

    
    @Column(name="idCliente", unique=true, nullable=false)
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="nombre", unique=true, nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="dni", unique=true, length=9)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

    
    @Column(name="direccion", length=70)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="telefono", length=9)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="poblacion", length=25)
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }

    
    @Column(name="subvencionado", nullable=false)
    public boolean isSubvencionado() {
        return this.subvencionado;
    }
    
    public void setSubvencionado(boolean subvencionado) {
        this.subvencionado = subvencionado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getMolturacions() {
        return this.molturacions;
    }
    
    public void setMolturacions(Set molturacions) {
        this.molturacions = molturacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getCambios() {
        return this.cambios;
    }
    
    public void setCambios(Set cambios) {
        this.cambios = cambios;
    }




}


