package pojos;
// Generated 13-sep-2016 20:37:20 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Molturacion generated by hbm2java
 */
@Entity
@Table(name="molturacion"
    ,catalog="almazaradb"
)
public class Molturacion  implements java.io.Serializable {


     private int idMolturacion;
     private Cliente cliente;
     private Usuario usuario;
     private float kgOvila;
     private float litrosAceiteProd;
     private float kgOrujo;
     private float ingresoMolturacion;
     private Date fecha;
     private boolean pagada;
     private boolean declara;
     private float kgReflejadosDeclaracion;
     private float maquila;
     private String observaciones;

    public Molturacion() {
    }

	
    public Molturacion(int idMolturacion, Cliente cliente, Usuario usuario, float kgOvila, float litrosAceiteProd, float kgOrujo, float ingresoMolturacion, Date fecha, boolean pagada, boolean declara, float kgReflejadosDeclaracion, float maquila) {
        this.idMolturacion = idMolturacion;
        this.cliente = cliente;
        this.usuario = usuario;
        this.kgOvila = kgOvila;
        this.litrosAceiteProd = litrosAceiteProd;
        this.kgOrujo = kgOrujo;
        this.ingresoMolturacion = ingresoMolturacion;
        this.fecha = fecha;
        this.pagada = pagada;
        this.declara = declara;
        this.kgReflejadosDeclaracion = kgReflejadosDeclaracion;
        this.maquila = maquila;
    }
    public Molturacion(int idMolturacion, Cliente cliente, Usuario usuario, float kgOvila, float litrosAceiteProd, float kgOrujo, float ingresoMolturacion, Date fecha, boolean pagada, boolean declara, float kgReflejadosDeclaracion, float maquila, String observaciones) {
       this.idMolturacion = idMolturacion;
       this.cliente = cliente;
       this.usuario = usuario;
       this.kgOvila = kgOvila;
       this.litrosAceiteProd = litrosAceiteProd;
       this.kgOrujo = kgOrujo;
       this.ingresoMolturacion = ingresoMolturacion;
       this.fecha = fecha;
       this.pagada = pagada;
       this.declara = declara;
       this.kgReflejadosDeclaracion = kgReflejadosDeclaracion;
       this.maquila = maquila;
       this.observaciones = observaciones;
    }
   
     @Id 

    
    @Column(name="idMolturacion", unique=true, nullable=false)
    public int getIdMolturacion() {
        return this.idMolturacion;
    }
    
    public void setIdMolturacion(int idMolturacion) {
        this.idMolturacion = idMolturacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Cliente_idCliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Usuario_idUsuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="kgOvila", nullable=false, precision=12, scale=0)
    public float getKgOvila() {
        return this.kgOvila;
    }
    
    public void setKgOvila(float kgOvila) {
        this.kgOvila = kgOvila;
    }

    
    @Column(name="litrosAceiteProd", nullable=false, precision=12, scale=0)
    public float getLitrosAceiteProd() {
        return this.litrosAceiteProd;
    }
    
    public void setLitrosAceiteProd(float litrosAceiteProd) {
        this.litrosAceiteProd = litrosAceiteProd;
    }

    
    @Column(name="kgOrujo", nullable=false, precision=12, scale=0)
    public float getKgOrujo() {
        return this.kgOrujo;
    }
    
    public void setKgOrujo(float kgOrujo) {
        this.kgOrujo = kgOrujo;
    }

    
    @Column(name="ingresoMolturacion", nullable=false, precision=12, scale=0)
    public float getIngresoMolturacion() {
        return this.ingresoMolturacion;
    }
    
    public void setIngresoMolturacion(float ingresoMolturacion) {
        this.ingresoMolturacion = ingresoMolturacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="Pagada", nullable=false)
    public boolean isPagada() {
        return this.pagada;
    }
    
    public void setPagada(boolean pagada) {
        this.pagada = pagada;
    }

    
    @Column(name="declara", nullable=false)
    public boolean isDeclara() {
        return this.declara;
    }
    
    public void setDeclara(boolean declara) {
        this.declara = declara;
    }

    
    @Column(name="kgReflejadosDeclaracion", nullable=false, precision=12, scale=0)
    public float getKgReflejadosDeclaracion() {
        return this.kgReflejadosDeclaracion;
    }
    
    public void setKgReflejadosDeclaracion(float kgReflejadosDeclaracion) {
        this.kgReflejadosDeclaracion = kgReflejadosDeclaracion;
    }

    
    @Column(name="maquila", nullable=false, precision=12, scale=0)
    public float getMaquila() {
        return this.maquila;
    }
    
    public void setMaquila(float maquila) {
        this.maquila = maquila;
    }

    
    @Column(name="Observaciones", length=100)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


