package pojos;
// Generated 13-sep-2016 20:37:20 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VentaHasProductoId generated by hbm2java
 */
@Embeddable
public class VentaHasProductoId  implements java.io.Serializable {


     private int ventaIdVenta;
     private int productoIdProducto;

    public VentaHasProductoId() {
    }

    public VentaHasProductoId(int ventaIdVenta, int productoIdProducto) {
       this.ventaIdVenta = ventaIdVenta;
       this.productoIdProducto = productoIdProducto;
    }
   


    @Column(name="Venta_idVenta", nullable=false)
    public int getVentaIdVenta() {
        return this.ventaIdVenta;
    }
    
    public void setVentaIdVenta(int ventaIdVenta) {
        this.ventaIdVenta = ventaIdVenta;
    }


    @Column(name="Producto_idProducto", nullable=false)
    public int getProductoIdProducto() {
        return this.productoIdProducto;
    }
    
    public void setProductoIdProducto(int productoIdProducto) {
        this.productoIdProducto = productoIdProducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VentaHasProductoId) ) return false;
		 VentaHasProductoId castOther = ( VentaHasProductoId ) other; 
         
		 return (this.getVentaIdVenta()==castOther.getVentaIdVenta())
 && (this.getProductoIdProducto()==castOther.getProductoIdProducto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getVentaIdVenta();
         result = 37 * result + this.getProductoIdProducto();
         return result;
   }   


}


