package pojos;
// Generated 15-sep-2016 21:42:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="producto"
    ,catalog="almazaradb"
)
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private String nombre;
     private float cantidad;
     private Set ventaHasProductos = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String nombre, float cantidad) {
        this.nombre = nombre;
        this.cantidad = cantidad;
    }
    public Producto(String nombre, float cantidad, Set ventaHasProductos) {
       this.nombre = nombre;
       this.cantidad = cantidad;
       this.ventaHasProductos = ventaHasProductos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idProducto", unique=true, nullable=false)
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="cantidad", nullable=false, precision=12, scale=0)
    public float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(float cantidad) {
        this.cantidad = cantidad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set getVentaHasProductos() {
        return this.ventaHasProductos;
    }
    
    public void setVentaHasProductos(Set ventaHasProductos) {
        this.ventaHasProductos = ventaHasProductos;
    }




}


